### ISSUE TITLE
[Block: 8393836] FTL Issue parsing a cosmos msg that we DO have a parser for! PLEASE INVESTIGATE

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#336] opened 2023-03-19 20:29 UTC
```
8:25PM INF Indexing 23 TXs from block 8393817.
8:25PM INF Indexing 4 TXs from block 8393820.
8:25PM INF Indexing 10 TXs from block 8393821.
8:25PM WRN Falling back to secondary queries for block height 8393836
Error: Log is invalid.
&{0 [{coin_spent [{spender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 6250uosmo}]} {coin_received [{receiver osmo17xpfvakm2amg962yls6f84z3kell8c5lczssa0} {amount 6250uosmo}]} {transfer [{recipient osmo17xpfvakm2amg962yls6f84z3kell8c5lczssa0} {sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 6250uosmo}]} {message [{sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr}]} {tx [{fee 6250uosmo}]} {tx [{acc_seq osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr/555}]} {tx [{signature RAnbxTOK5vUSSnXqBQZAoiK8HQ6k1VFhXjImWSPzh7IvrDY4HyK17QQZRdqK1VyGGGHTYOwQYFupy74vlRCtYg==}]} {message [{action /osmosis.gamm.v1beta1.MsgSwapExactAmountIn}]} {coin_spent [{spender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2}]} {coin_received [{receiver osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {amount 385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2}]} {transfer [{recipient osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2}]} {message [{sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr}]} {coin_spent [{spender osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {amount 5189734uosmo}]} {coin_received [{receiver osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 5189734uosmo}]} {transfer [{recipient osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {sender osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {amount 5189734uosmo}]} {message [{sender osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t}]} {token_swapped [{module gamm} {sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {pool_id 1} {tokens_in 385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2} {tokens_out 5189734uosmo}]} {message [{module gamm} {sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr}]}]}
Error: Log is invalid.
&{0 [{coin_spent [{spender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 6250uosmo}]} {coin_received [{receiver osmo17xpfvakm2amg962yls6f84z3kell8c5lczssa0} {amount 6250uosmo}]} {transfer [{recipient osmo17xpfvakm2amg962yls6f84z3kell8c5lczssa0} {sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 6250uosmo}]} {message [{sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr}]} {tx [{fee 6250uosmo}]} {tx [{acc_seq osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr/555}]} {tx [{signature RAnbxTOK5vUSSnXqBQZAoiK8HQ6k1VFhXjImWSPzh7IvrDY4HyK17QQZRdqK1VyGGGHTYOwQYFupy74vlRCtYg==}]} {message [{action /osmosis.gamm.v1beta1.MsgSwapExactAmountIn}]} {coin_spent [{spender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2}]} {coin_received [{receiver osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {amount 385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2}]} {transfer [{recipient osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2}]} {message [{sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr}]} {coin_spent [{spender osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {amount 5189734uosmo}]} {coin_received [{receiver osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 5189734uosmo}]} {transfer [{recipient osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {sender osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {amount 5189734uosmo}]} {message [{sender osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t}]} {token_swapped [{module gamm} {sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {pool_id 1} {tokens_in 385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2} {tokens_out 5189734uosmo}]} {message [{module gamm} {sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr}]}]}
Error: Log is invalid.
&{0 [{coin_spent [{spender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 6250uosmo}]} {coin_received [{receiver osmo17xpfvakm2amg962yls6f84z3kell8c5lczssa0} {amount 6250uosmo}]} {transfer [{recipient osmo17xpfvakm2amg962yls6f84z3kell8c5lczssa0} {sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 6250uosmo}]} {message [{sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr}]} {tx [{fee 6250uosmo}]} {tx [{acc_seq osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr/555}]} {tx [{signature RAnbxTOK5vUSSnXqBQZAoiK8HQ6k1VFhXjImWSPzh7IvrDY4HyK17QQZRdqK1VyGGGHTYOwQYFupy74vlRCtYg==}]} {message [{action /osmosis.gamm.v1beta1.MsgSwapExactAmountIn}]} {coin_spent [{spender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2}]} {coin_received [{receiver osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {amount 385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2}]} {transfer [{recipient osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2}]} {message [{sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr}]} {coin_spent [{spender osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {amount 5189734uosmo}]} {coin_received [{receiver osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 5189734uosmo}]} {transfer [{recipient osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {sender osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {amount 5189734uosmo}]} {message [{sender osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t}]} {token_swapped [{module gamm} {sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {pool_id 1} {tokens_in 385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2} {tokens_out 5189734uosmo}]} {message [{module gamm} {sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr}]}]}
8:25PM ERR [Block: 8393836] ParseCosmosMessage failed for msg of type '/osmosis.gamm.v1beta1.MsgSwapExactAmountIn'. error="Type: /osmosis.gamm.v1beta1.MsgSwapExactAmountIn could not handle message log &{MessageIndex:0 Events:[{Type:coin_spent Attributes:[{Key:spender Value:osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {Key:amount Value:6250uosmo}]} {Type:coin_received Attributes:[{Key:receiver Value:osmo17xpfvakm2amg962yls6f84z3kell8c5lczssa0} {Key:amount Value:6250uosmo}]} {Type:transfer Attributes:[{Key:recipient Value:osmo17xpfvakm2amg962yls6f84z3kell8c5lczssa0} {Key:sender Value:osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {Key:amount Value:6250uosmo}]} {Type:message Attributes:[{Key:sender Value:osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr}]} {Type:tx Attributes:[{Key:fee Value:6250uosmo}]} {Type:tx Attributes:[{Key:acc_seq Value:osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr/555}]} {Type:tx Attributes:[{Key:signature Value:RAnbxTOK5vUSSnXqBQZAoiK8HQ6k1VFhXjImWSPzh7IvrDY4HyK17QQZRdqK1VyGGGHTYOwQYFupy74vlRCtYg==}]} {Type:message Attributes:[{Key:action Value:/osmosis.gamm.v1beta1.MsgSwapExactAmountIn}]} {Type:coin_spent Attributes:[{Key:spender Value:osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {Key:amount Value:385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2}]} {Type:coin_received Attributes:[{Key:receiver Value:osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {Key:amount Value:385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2}]} {Type:transfer Attributes:[{Key:recipient Value:osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {Key:sender Value:osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {Key:amount Value:385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2}]} {Type:message Attributes:[{Key:sender Value:osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr}]} {Type:coin_spent Attributes:[{Key:spender Value:osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {Key:amount Value:5189734uosmo}]} {Type:coin_received Attributes:[{Key:receiver Value:osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {Key:amount Value:5189734uosmo}]} {Type:transfer Attributes:[{Key:recipient Value:osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {Key:sender Value:osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {Key:amount Value:5189734uosmo}]} {Type:message Attributes:[{Key:sender Value:osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t}]} {Type:token_swapped Attributes:[{Key:module Value:gamm} {Key:sender Value:osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {Key:pool_id Value:1} {Key:tokens_in Value:385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2} {Key:tokens_out Value:5189734uosmo}]} {Type:message Attributes:[{Key:module Value:gamm} {Key:sender Value:osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr}]}]}\n"
8:25PM ERR [Block: 8393836] ParseCosmosMessage failed for msg of type '/osmosis.gamm.v1beta1.MsgSwapExactAmountIn'.
8:25PM ERR &{0 [{coin_spent [{spender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 6250uosmo}]} {coin_received [{receiver osmo17xpfvakm2amg962yls6f84z3kell8c5lczssa0} {amount 6250uosmo
}]} {transfer [{recipient osmo17xpfvakm2amg962yls6f84z3kell8c5lczssa0} {sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 6250uosmo}]} {message [{sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr}]} {tx [{fee 6250uosmo}]} {tx [{acc_seq osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr/555}]} {tx [{signature RAnbxTOK5vUSSnXq
BQZAoiK8HQ6k1VFhXjImWSPzh7IvrDY4HyK17QQZRdqK1VyGGGHTYOwQYFupy74vlRCtYg==}]} {message [{action /osmosis.gamm.v1beta1.MsgSwapExactAmountIn}]} {coin_spent [{spender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2}]} {coin_received [{receiver osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {amount 385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2}]} {transfer [{recipient osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2}]} {message [{sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr}]} {coin_spent [{spender osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {amount 5189734uosmo}]} {coin_received [{receiver osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {amount 5189734uosmo}]} {transfer [{recipient osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {sender osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t} {amount 5189734uosmo}]} {message [{sender osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t}]} {token_swapped [{module gamm} {sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr} {pool_id 1} {tokens_in 385544ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2} {tokens_out 5189734uosmo}]} {message [{module gamm} {sender osmo1323790xwgfyg0qs694s9c5rfzq376vvh3mqncr}]}]}
8:25PM ERR BWfHq90o/8TMHLYRe1dXjVxKIDFkTRuQRNWSP/ymruQ=
8:25PM FTL Issue parsing a cosmos msg that we DO have a parser for! PLEASE INVESTIGATE
```

**Comment by pharr117** [comment] 2023-03-23 04:11
I have dug into this one and figured out the issue.

## Actions I took:
1. Comment out the normal code for getting blocks
2. Force it down the path that caused the error we see above

## Explanation

The index command has a fallback option when it fails to get Blocks for whatever reason (usually an invalid response from RPC `GetTxsByBlockHeight`), which we reached at this fatal error. See [this](https://github.com/DefiantLabs/cosmos-tax-cli/blob/main/cmd/index.go#L471) block of code.

We fall back to a `GetBlock` RPC request, where we then process the raw RPC block TXs into their proper types.

However, the `GetBlock` response seems to give back a bunch more data in the event log than is normally received by the transactions coming in from `GetTxsByBlockHeight`.

## Root Cause

The root cause of the "Log is invalid" fatal error is due to us finding the first "message" event in the logs during pre-validation of the event.

1. In the normal `GetTxsByBlockHeight` response, there is a single "message" event that contains the "action" attribute. We use this to verify the action is what we expect.
3. In the `GetBlock` response, there are multiple "message" events, each with wildly different attributes. This causes the error we see above.

So I tried to do the following:
1. Improve `IsMessageActionEquals` found [here](https://github.com/DefiantLabs/cosmos-tax-cli/blob/main/cosmos/modules/tx/logic.go#L100) by finding all the "message" actions and looping through until it found the "action" attribute
2. This fixes the pre-validation

## Further Issues

However, another problem popped up:

1. I compared a normal run down the good path of `GetTxsByBlockHeight` and the bad path of `GetBlock` and post-process
2. The output of the indexer is completely different. 

Normal Run:

```
11:37PM DBG [Block: 8393836] Cosmos message of known type: MsgWithdrawDelegatorReward: Delegator osmo1r9a6xjlknunsjrw29rzk3fqjjprw0ujw9w483d received 51117uosmo

11:37PM DBG [Block: 8393836] Cosmos message of known type: MsgWithdrawDelegatorReward: Delegator osmo1r9a6xjlknunsjrw29rzk3fqjjprw0ujw9w483d received 50863uosmo

11:37PM DBG [Block: 8393836] Cosmos message of known type: MsgWithdrawDelegatorReward: Delegator osmo1r9a6xjlknunsjrw29rzk3fqjjprw0ujw9w483d received 26067uosmo
```

Bad path:
```
11:36PM DBG [Block: 8393836] Cosmos message of known type: MsgWithdrawDelegatorReward: Delegator osmo1r9a6xjlknunsjrw29rzk3fqjjprw0ujw9w483d received 18355uosmo

11:36PM DBG [Block: 8393836] Cosmos message of known type: MsgWithdrawDelegatorReward: Delegator osmo1r9a6xjlknunsjrw29rzk3fqjjprw0ujw9w483d received 18355uosmo

11:36PM DBG [Block: 8393836] Cosmos message of known type: MsgWithdrawDelegatorReward: Delegator osmo1r9a6xjlknunsjrw29rzk3fqjjprw0ujw9w483d received 18355uosmo
```

Completely different results.

## Further Root Cause

This new issue pops up because:

1. We get the amount of tokens from the "transfer" event in `MsgWithdrawDelegatorRewards`
2. In the normal `GetTxsByBlockHeight` there is only ever 1 transfer event. This contains the actual amount of rewards received
3. In the `GetBlocks` response, there are several, each with different values only 1 of which is the actual reward received
4. We find the first one and call it a day, which works with (2) above, but not (3)

If you look at this picture, the bad path output is actually the fee amount, 18355:

![image](https://user-images.githubusercontent.com/24580777/227100655-de4741d4-e99f-4abd-9cd9-ed45cb12a0d6.png)

## Conclusion

I think we need to eliminate this fallback option of using `GetBlock`. It seems to find a lot more events than the normal path, most likely because it is gathering ALL events that took place for the transaction including high level events like fee transfers, while the `GetTxsByBlockHeight` path only returns the relevant TX events we have designed the code to expect.

**Comment by pharr117** [comment] 2023-03-23 04:23
Another thing to note, which could imply something different than the above if I am incorrect on anything:

The transaction in question was a single transaction with multiple messages.

![image](https://user-images.githubusercontent.com/24580777/227102230-ce96bdf4-3a0c-4ea7-8ba3-98ad805f41c9.png)

## In the logs:

I notice also that when the log events get parsed in our code, all 3 of these messages contain the events of the others.

This could just be us handling the log events incorrectly.

**Comment by KyleMoser** [comment] 2023-03-24 02:04
When you circle back to this one, I pushed my changes to main, so the events should all be returned the same way regardless of which RPC endpoint gets called now.

**Comment by pharr117** [comment] 2023-03-25 18:42
With Kyle's push to main, I have confirmed that this block is properly parsed with:

1. The normal block processor
2. The alternate block processer when (1) fails

**Comment by pharr117** [comment] 2023-04-11 01:47
Closing due to the above comment

**Closed as completed by pharr117** 2023-04-11 01:47 UTC
