### ISSUE TITLE
Re-index failed messages

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#466] opened 2023-09-02 19:11 UTC
The follow messages failed to index when the archive server was running:

```
/osmosis.poolmanager.v1beta1.MsgSplitRouteSwapExactAmountIn
...
```

Use:
https://osmosisarchive-rpc.quickapi.com:443 to reindex all failed messages into production DB.

**Comment by pharr117** [comment] 2023-09-12 02:05
We are tracking the following message types as well:

Error parsing Osmosis transaction with possible Lens codec issues:
```
Error getting transactions by block height (11093463). Err: rpc error: code = InvalidArgument desc = errUnknownField "*types.PoolRecord": {TagNum: 4, WireType:"bytes"}: tx parse error: invalid request. Will reattempt
```

Another Lens codec issue, this time with the superfluid module:
```
ERR Block 11339595 failed. Reason: {unknown error} error="tx message could not be processed. CachedValue is not present. TX Hash: 0C3EF7802840DB3B6422B7EA7BBB1F297952D0AD0C212C14C8FD3268EE514EBC, Msg type: /osmosis.superfluid.MsgUnbondConvertAndStake, Msg index:
```

Lens codec issue, this time with the base Cosmos gov module:

```
ERR ProcessRpcTxs: unhandled error error="tx message could not be processed. CachedValue is not present. TX Hash: 5B040C19566DA8572FE5303621DAC166256BEEAFAD3820AACFE4BDAD08739640, Msg type: /cosmos.gov.v1beta1.MsgSubmitProposal, Msg index: 0, Code: 0" 
```

**Comment by pharr117** [comment] 2023-09-26 23:19
The final failed message we are tracking is the failed block caused by the transaction here:

5B040C19566DA8572FE5303621DAC166256BEEAFAD3820AACFE4BDAD08739640

The root cause of this one is that Osmosis changed the fields on the proto definition of one of their custom Proposal types. Due to this, the gov module cannot decode the TX during RPC requests and the RPC request fails.

See [here](https://github.com/osmosis-labs/osmosis/commit/9a48b4c9b39af36bd9746c85e715a11a56a031bb) for their removed field.

This one will be much more complicated to solve, so I will close this one out and open a separate ticket for that.

**Closed as completed by pharr117** 2023-09-26 23:19 UTC
Labels: bug, OGP, 2023
