### ISSUE TITLE
[9101787] - panic: invalid denom: cw20:juno1mkw83sv6c7sjdvsaplrzc8yaes9l42p4mhy0ssuxjnyzl87c9eps7ce3m9

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#413] opened 2023-05-15 15:40 UTC
![image](https://github.com/DefiantLabs/cosmos-tax-cli/assets/807940/8e3ace14-8a43-4a06-b84d-f7a2c32c8a0e)

**Comment by pharr117** [comment] 2023-05-15 22:20
The block is actually `9101787` (our indexer is running multithreaded, so its a bit misleading which block failed in the output screenshot)

**Comment by pharr117** [comment] 2023-05-15 23:50
This one is a bit involved.

The offending line is here: https://github.com/DefiantLabs/cosmos-tax-cli/blob/9bef83ce2acb2a08fdd6127dc1861de4ed861688/cosmos/modules/ibc/types.go#L120

Root cause:

* We had decided to import the Osmosis fork of Cosmos SDK a while ago
* We use this version of the Cosmos SDK for all of our Cosmos functionality
* We use cosmos-sdk NewCoin in a few places to get the Coin type from an amount and a denom
* Osmosis' version of NewCoin is very old, using a Regex to validate the denom that is very old - [source](https://github.com/osmosis-labs/cosmos-sdk/blob/8a66b9a200c2aacd35ac0a3f2b9cca5f55325189/types/coin.go#L773)
* This Regex does not allow ":", which is integral to cw20 tokens
* The Cosmos SDK added this feature around 20 months ago - [source](https://github.com/cosmos/cosmos-sdk/blob/bf3749207ef38cc98a0df8183984ef869912a38e/types/coin.go#L831)

The fix for this will be either:

1. Stop using NewCoin, we don't *really* need it, it just helps to use the underlying type
2. Strip out our dependency on Osmosis' fork of Cosmos SDK, import the current release of Cosmos SDK and use that instead

(1) would be easy most likely, but not robust. This may be the way to go as a hotfix
(2) would be hard and take a lot of work, but is probably what needs to be done. It will take the following:

1. Strip out the Osmosis Cosmos SDK fork from this repo and our Lens fork
2. Rework the entirety of our Lens fork to use protobuf generated message types for all Osmosis modules we need to support
3. Use the actual Cosmos SDK package instead :arrow_right: will fix our NewCoin problem
4. Fix all of the places (if any) that the code is not compatible with the actual Cosmos SDK. (We became reliant on Osmosis' fork, so some code may not be correct in the current release of Cosmos SDK)

**Comment by danbryan** [comment] 2023-05-16 00:40
I agree, option 2 is the way to go, lets move forward on that.  Curious, for the time being can we add a skip for cw20 tokens to allow indexing of everything else for april/may.

**Closed as completed** 2023-05-28 22:00 UTC
Labels: bug, 2023
