### ISSUE TITLE
Block [2723463] -  /osmosis.gamm.v1beta1.MsgCreatePool

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#347] opened 2023-03-24 22:57 UTC
block `2723463` seems to have multiple issues. The first was resolved already i this ticket.

https://github.com/DefiantLabs/cosmos-tax-cli/issues/328 by @KyleMoser 

now, the same block is failing with this error.
```
cosmos-tax-cli-indexer-1   | 6:50PM INF Indexing Rewards from block: 2723462 to 2723463
cosmos-tax-cli-indexer-1   | 6:50PM INF Hit the last block we're allowed to index, exiting enqueue func.
cosmos-tax-cli-indexer-1   | 6:50PM INF Indexing 3 TXs from block 2723462.
cosmos-tax-cli-indexer-1   | 6:50PM WRN Falling back to secondary queries for block height 2723463
cosmos-tax-cli-indexer-1   | 6:50PM ERR [Block: 2723463] ParseCosmosMessage failed for msg of type '/osmosis.gamm.v1beta1.MsgCreatePool'. error="Type: /osmosis.gamm.v1beta1.MsgCreatePool could not handle message log &{MessageIndex:0 Events:[{Type:tx Attributes:[{Key:fee Value:0uosmo}]} {Type:tx Attributes:[{Key:acc_seq Value:osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw/2}]} {Type:tx Attributes:[{Key:signature Value:ri+6unge0P5rd26hGjMP1YyGbdC+gK4OykxfN+ZJcWlwNU00V3w/E0mxj5e+Z0ovZEYDEHuPiZ/wag0ShYUU+A==}]} {Type:message Attributes:[{Key:action Value:/osmosis.gamm.v1beta1.MsgCreatePool}]} {Type:coin_spent Attributes:[{Key:spender Value:osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw} {Key:amount Value:100000000uosmo}]} {Type:coin_received Attributes:[{Key:receiver Value:osmo1jv65s3grqf6v6jl3dp4t6c9t9rk99cd80yhvld} {Key:amount Value:100000000uosmo}]} {Type:transfer Attributes:[{Key:recipient Value:osmo1jv65s3grqf6v6jl3dp4t6c9t9rk99cd80yhvld} {Key:sender Value:osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw} {Key:amount Value:100000000uosmo}]} {Type:message Attributes:[{Key:sender Value:osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw}]} {Type:coin_spent Attributes:[{Key:spender Value:osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw} {Key:amount Value:3000000000ibc/E7B35499CFBEB0FF5778127ABA4FB2C4B79A6B8D3D831D4379C4048C238796BD,92000000uosmo}]} {Type:coin_received Attributes:[{Key:receiver Value:osmo17sk5nv9367kc5jgfmtf64c9esgf4sdeazd8fd5twrlhxqne3tgnqrp2qpz} {Key:amount Value:3000000000ibc/E7B35499CFBEB0FF5778127ABA4FB2C4B79A6B8D3D831D4379C4048C238796BD,92000000uosmo}]} {Type:transfer Attributes:[{Key:recipient Value:osmo17sk5nv9367kc5jgfmtf64c9esgf4sdeazd8fd5twrlhxqne3tgnqrp2qpz} {Key:sender Value:osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw} {Key:amount Value:3000000000ibc/E7B35499CFBEB0FF5778127ABA4FB2C4B79A6B8D3D831D4379C4048C238796BD,92000000uosmo}]} {Type:message Attributes:[{Key:sender Value:osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw}]} {Type:coin_received Attributes:[{Key:receiver Value:osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj} {Key:amount Value:100000000000000000000gamm/pool/613}]} {Type:coinbase Attributes:[{Key:minter Value:osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj} {Key:amount Value:100000000000000000000gamm/pool/613}]} {Type:coin_spent Attributes:[{Key:spender Value:osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj} {Key:amount Value:100000000000000000000gamm/pool/613}]} {Type:coin_received Attributes:[{Key:receiver Value:osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw} {Key:amount Value:100000000000000000000gamm/pool/613}]} {Type:transfer Attributes:[{Key:recipient Value:osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw} {Key:sender Value:osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj} {Key:amount Value:100000000000000000000gamm/pool/613}]} {Type:message Attributes:[{Key:sender Value:osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj}]} {Type:coin_spent Attributes:[{Key:spender Value:osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9} {Key:amount Value:}]} {Type:coin_received Attributes:[{Key:receiver Value:osmo1krxwf5e308jmclyhfd9u92kp369l083wequge6} {Key:amount Value:}]} {Type:transfer Attributes:[{Key:recipient Value:osmo1krxwf5e308jmclyhfd9u92kp369l083wequge6} {Key:sender Value:osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9} {Key:amount Value:}]} {Type:message Attributes:[{Key:sender Value:osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9}]} {Type:coin_spent Attributes:[{Key:spender Value:osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9} {Key:amount Value:}]} {Type:coin_received Attributes:[{Key:receiver Value:osmo1krxwf5e308jmclyhfd9u92kp369l083wequge6} {Key:amount Value:}]} {Type:transfer Attributes:[{Key:recipient Value:osmo1krxwf5e308jmclyhfd9u92kp369l083wequge6} {Key:sender Value:osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9} {Key:amount Value:}]} {Type:message Attributes:[{Key:sender Value:osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9}]} {Type:coin_spent Attributes:[{Key:spender Value:osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9} {Key:amount Value:}]} {Type:coin_received Attributes:[{Key:receiver Value:osmo1krxwf5e308jmclyhfd9u92kp369l083wequge6} {Key:amount Value:}]} {Type:transfer Attributes:[{Key:recipient Value:osmo1krxwf5e308jmclyhfd9u92kp369l083wequge6} {Key:sender Value:osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9} {Key:amount Value:}]} {Type:message Attributes:[{Key:sender Value:osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9}]} {Type:pool_created Attributes:[{Key:pool_id Value:613}]} {Type:message Attributes:[{Key:module Value:gamm} {Key:sender Value:osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw}]}]}\n"
cosmos-tax-cli-indexer-1   | 6:50PM ERR [Block: 2723463] ParseCosmosMessage failed for msg of type '/osmosis.gamm.v1beta1.MsgCreatePool'.
cosmos-tax-cli-indexer-1   | 6:50PM ERR &{0 [{tx [{fee 0uosmo}]} {tx [{acc_seq osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw/2}]} {tx [{signature ri+6unge0P5rd26hGjMP1YyGbdC+gK4OykxfN+ZJcWlwNU00V3w/E0mxj5e+Z0ovZEYDEHuPiZ/wag0ShYUU+A==}]} {message [{action /osmosis.gamm.v1beta1.MsgCreatePool}]} {coin_spent [{spender osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw} {amount 100000000uosmo}]} {coin_received [{receiver osmo1jv65s3grqf6v6jl3dp4t6c9t9rk99cd80yhvld} {amount 100000000uosmo}]} {transfer [{recipient osmo1jv65s3grqf6v6jl3dp4t6c9t9rk99cd80yhvld} {sender osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw} {amount 100000000uosmo}]} {message [{sender osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw}]} {coin_spent [{spender osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw} {amount 3000000000ibc/E7B35499CFBEB0FF5778127ABA4FB2C4B79A6B8D3D831D4379C4048C238796BD,92000000uosmo}]} {coin_received [{receiver osmo17sk5nv9367kc5jgfmtf64c9esgf4sdeazd8fd5twrlhxqne3tgnqrp2qpz} {amount 3000000000ibc/E7B35499CFBEB0FF5778127ABA4FB2C4B79A6B8D3D831D4379C4048C238796BD,92000000uosmo}]} {transfer [{recipient osmo17sk5nv9367kc5jgfmtf64c9esgf4sdeazd8fd5twrlhxqne3tgnqrp2qpz} {sender osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw} {amount 3000000000ibc/E7B35499CFBEB0FF5778127ABA4FB2C4B79A6B8D3D831D4379C4048C238796BD,92000000uosmo}]} {message [{sender osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw}]} {coin_received [{receiver osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj} {amount 100000000000000000000gamm/pool/613}]} {coinbase [{minter osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj} {amount 100000000000000000000gamm/pool/613}]} {coin_spent [{spender osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj} {amount 100000000000000000000gamm/pool/613}]} {coin_received [{receiver osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw} {amount 100000000000000000000gamm/pool/613}]} {transfer [{recipient osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw} {sender osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj} {amount 100000000000000000000gamm/pool/613}]} {message [{sender osmo1c9y7crgg6y9pfkq0y8mqzknqz84c3etr0kpcvj}]} {coin_spent [{spender osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9} {amount }]} {coin_received [{receiver osmo1krxwf5e308jmclyhfd9u92kp369l083wequge6} {amount }]} {transfer [{recipient osmo1krxwf5e308jmclyhfd9u92kp369l083wequge6} {sender osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9} {amount }]} {message [{sender osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9}]} {coin_spent [{spender osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9} {amount }]} {coin_received [{receiver osmo1krxwf5e308jmclyhfd9u92kp369l083wequge6} {amount }]} {transfer [{recipient osmo1krxwf5e308jmclyhfd9u92kp369l083wequge6} {sender osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9} {amount }]} {message [{sender osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9}]} {coin_spent [{spender osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9} {amount }]} {coin_received [{receiver osmo1krxwf5e308jmclyhfd9u92kp369l083wequge6} {amount }]} {transfer [{recipient osmo1krxwf5e308jmclyhfd9u92kp369l083wequge6} {sender osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9} {amount }]} {message [{sender osmo1upfuxznarpja3sywq0tzd2kktg9wv8mcc0rlm9}]} {pool_created [{pool_id 613}]} {message [{module gamm} {sender osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw}]}]}
cosmos-tax-cli-indexer-1   | 6:50PM ERR OOG7wKzifYqfqdrwPQterVWioVD23Z921qxFcZXMRDk=
cosmos-tax-cli-indexer-1   | 6:50PM FTL Issue parsing a cosmos msg that we DO have a parser for! PLEASE INVESTIGATE
```

**Comment by danbryan** [comment] 2023-03-24 23:08
did this old fix get removed from main somehow?
https://github.com/DefiantLabs/cosmos-tax-cli/pull/325

**Comment by KyleMoser** [comment] 2023-03-24 23:20
```
{"level":"info","time":"2023-03-24T19:19:05-04:00","message":"Updating Denom Metadata from http://34.168.39.1:1317"}
{"level":"info","time":"2023-03-24T19:19:05-04:00","message":"Hit the last block we're allowed to index, exiting enqueue func."}
{"level":"warn","time":"2023-03-24T19:19:06-04:00","message":"Falling back to secondary queries for block height 2723463"}
{"level":"debug","time":"2023-03-24T19:19:06-04:00","message":"[Block: 2723463] Cosmos message of known type: MsgCreatePool: osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw created pool with 92000000uosmo, 3000000000ibc/E7B35499CFBEB0FF5778127ABA4FB2C4B79A6B8D3D831D4379C4048C238796BD\n"}
{"level":"debug","time":"2023-03-24T19:19:06-04:00","message":"[Block: 2723463] Cosmos message of known type: MsgDelegate: Delegator osmo1espd3tmahfpe7074nqhzulcu5fdvhm48trrg3t auto-withdrew 9959uosmo\n"}
{"level":"debug","time":"2023-03-24T19:19:06-04:00","message":"[Block: 2723463] Cosmos message of known type: MsgSwapExactAmountIn: osmo1l2wvt0ara5l5he76p0aldzg2jwm980ynaqcpxt swapped in 323uion and received 1936666ibc/1480B8FD20AD5FCAE81EA87584D269547DD4D436843C1D20F15E00EB64743EF4\n"}
{"level":"debug","time":"2023-03-24T19:19:06-04:00","message":"[Block: 2723463] Cosmos message of known type: MsgDelegate: Delegator osmo1hd3qsm0e2eslz203ykln3e9crcglyswk4sf927 did not auto-withdrawal rewards\n"}
{"level":"debug","time":"2023-03-24T19:19:06-04:00","message":"[Block: 2723463] Cosmos message of known type: MsgJoinPool: osmo1uj7xf8hzm2nxhqvwv3h7zhgypffr2kswtjkdyw joined pool with 7722086ibc/EA3E1640F9B1532AB129A571203A0B9F789A7F14BB66E350DCBFA18E1A1931F0, 4556245uosmo and received 151377309775152225gamm/pool/601\n"}
```

works for me

**Comment by pharr117** [comment] 2023-04-11 01:52
I just confirmed this block is working as expected, closing this out.

```
9:51PM INF Hit the last block we're allowed to index, exiting enqueue func.
9:51PM DBG Falling back to secondary queries for block height 2723463
9:51PM DBG [Block: 2723463] Cosmos message of known type: MsgCreatePool: osmo1l23c9md9fvseymunfs3xn765vjqkr4sqdtsuuw created pool with 92000000uosmo, 3000000000ibc/E7B35499CFBEB0FF5778127ABA4FB2C4B79A6B8D3D831D4379C4048C238796BD

9:51PM WRN Denom lookup failed. Will be inserted as UNKNOWN. Denom Received: gamm/pool/613. Err: GetDenomForBase: no denom unit for the specified denom gamm/pool/613
9:51PM DBG [Block: 2723463] Cosmos message of known type: MsgDelegate: Delegator osmo1espd3tmahfpe7074nqhzulcu5fdvhm48trrg3t auto-withdrew 9959uosmo

9:51PM DBG [Block: 2723463] Cosmos message of known type: MsgSwapExactAmountIn: osmo1l2wvt0ara5l5he76p0aldzg2jwm980ynaqcpxt swapped in 323uion and received 1936666ibc/1480B8FD20AD5FCAE81EA87584D269547DD4D436843C1D20F15E00EB64743EF4

9:51PM DBG [Block: 2723463] Cosmos message of known type: MsgDelegate: Delegator osmo1hd3qsm0e2eslz203ykln3e9crcglyswk4sf927 did not auto-withdrawal rewards

9:51PM DBG [Block: 2723463] Cosmos message of known type: MsgJoinPool: osmo1uj7xf8hzm2nxhqvwv3h7zhgypffr2kswtjkdyw joined pool with 7722086ibc/EA3E1640F9B1532AB129A571203A0B9F789A7F14BB66E350DCBFA18E1A1931F0, 4556245uosmo and received 151377309775152225gamm/pool/601

9:51PM WRN Denom lookup failed. Will be inserted as UNKNOWN. Denom Received: gamm/pool/601. Err: GetDenomForBase: no denom unit for the specified denom gamm/pool/601
9:51PM INF Indexing 11 TXs from block 2723463
```

**Closed as completed by pharr117** 2023-04-11 01:52 UTC
Labels: bug, osmosis-1, 2023
